eliashaeussler/typo3-warming

- Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php
- Classes/Cache/CacheManager.php
- Tests/Unit/Cache/CacheManagerTest.php
- Tests/Unit/Sitemap/SitemapLocatorTest.php
- composer.json
This PR upgrades PHPStan and extensions to 1.x.
> [FEATURE] Upgrade to PHPStan 1.x

- .github/CODE_OF_CONDUCT.md
This PR streamlines the Code of Conduct of this extension with the [official document from TYPO3 core](https://github.com/TYPO3/typo3/blob/6963edadb278e6f39f00d52725aa042d3b5bdf21/CODE_OF_CONDUCT.md).
> [TASK] Streamline Code of Conduct with TYPO3 core

- .github/workflows/cgl.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- composer.json
This PR adds compatibility with PHP 8.1.
> [FEATURE] Add compatibility with PHP 8.1

- .github/dependabot.yml
This PR enables automated Dependabot updates for GitHub Actions.
> [FEATURE] Enable Dependabot for GitHub Actions

- Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php
- Classes/Cache/CacheManager.php
- Classes/Command/WarmupCommand.php
- Classes/Controller/CacheWarmupController.php
- Classes/Crawler/RequestAwareTrait.php
- Classes/Service/CacheWarmupService.php
- Classes/Sitemap/Provider/AbstractProvider.php
- Classes/Sitemap/Provider/SiteProvider.php
- Classes/Sitemap/SitemapLocator.php
- Classes/Utility/AccessUtility.php
This PR aligns the code base with latest changes in typo3/coding-standards library.
> [BUGFIX] Align with latest changes in typo3/coding-standards

- .github/dependabot.yml
- .github/workflows/dependabot.yaml
With this PR, Dependabot updates for Frontend resources are activated. On each Dependabot update, the dist files will be re-created.
> [TASK] Configure Dependabot update for Frontend resources

- .github/dependabot.yml
- .github/workflows/release.yaml
- Resources/Private/Libs/Build/composer.json
- Resources/Private/Libs/Build/composer.lock
With this PR, Dependabot support for TER libraries is added.
> [TASK] Let Dependabot manage TER libraries

- .github/workflows/cgl.yaml
This PR adds linting of Frontend source files to the CGL workflow.
> [TASK] Lint Frontend sources in CGL workflow

- Classes/Command/WarmupCommand.php
- Classes/Controller/CacheWarmupController.php
- Classes/Service/CacheWarmupService.php
- phpstan.neon
This PR upgrades the codebase for compliance with PHPStan level 8.
> [TASK] Upgrade to PHPStan level 8

- .github/workflows/cgl.yaml
- Classes/Cache/CacheManager.php
- Classes/Configuration/Configuration.php
- Tests/Build/Installation/install-steps.yaml
- Tests/Build/Stubs/TYPO3/PharStreamWrapper/PharStreamWrapper.php
- Tests/Build/console-application.php
- composer.json
- phpstan.neon
This PR upgrades the codebase for compliance with PHPStan max level.
> [TASK] Upgrade to PHPStan max level

- Classes/Sitemap/SitemapLocator.php
> [BUGFIX] Only include enabled languages

- composer.json
- phpstan.neon
This PR adds PHPStan extension installer to automatically manage PHPStan extensions.
> [TASK] Use PHPStan extension installer

- .github/workflows/tests.yaml
- composer.json
This PR adds support for PHP 8.2.
> [FEATURE] Add support for PHP 8.2

- .github/workflows/cgl.yaml
This reverts commit d4d3e366652b3a8a9c9312de71aee80172f59a69.
> Revert "[TASK] Use composer-unused 0.7 in CI"

- .github/workflows/cgl.yaml
- .github/workflows/tests.yaml
- rector.php
All GitHub workflows now use PHP 8.2.
> [TASK] Run GitHub workflows with PHP 8.2

- Classes/Event/AfterCacheWarmupEvent.php
- Classes/Event/BeforeCacheWarmupEvent.php
- Classes/Service/CacheWarmupService.php
- Configuration/Services.yaml
- Documentation/DeveloperCorner/Events.rst
- Documentation/DeveloperCorner/Index.rst
- Tests/Functional/Controller/CacheWarmupLegacyControllerTest.php
- Tests/Functional/Fixtures/Classes/DummyEventDispatcher.php
- Tests/Functional/Service/CacheWarmupServiceTest.php
- composer.json
This PR adds events to step in the cache warmup lifecycle.
> [FEATURE] Introduce events

- composer.json
- phpstan-baseline.neon
This PR includes the `phpstan/phpstan-phpunit` package for static code analysis with PHPStan.
> [TASK] Include phpstan/phpstan-phpunit

- Documentation/Usage/Index.rst
Das fehlt mir da als Hinweis :wink:
> [DOCS] Add note that sitemap is needed for usage

- .gitattributes
- .github/workflows/cgl.yaml
- .github/workflows/renovate.yaml
- .gitignore
- composer.lock
This PR adds a `composer.lock` file to better verify CGL issues in dependency updates.
> [TASK] Add `composer.lock` file

- Documentation/DeveloperCorner/Crawlers.rst
This PR adds stoppable crawlers (introduced with eliashaeussler/cache-warmup#302) to the documentation.
> [DOCS] Document stoppable crawlers

- Documentation/Configuration/ExtensionConfiguration.rst
- Documentation/Usage/ConsoleCommands.rst
> [DOCS] Add documentation for usage in deployment processes

- Documentation/Configuration/ExtensionConfiguration.rst
- Documentation/DeveloperCorner/AccessUtility.rst
- Documentation/DeveloperCorner/Crawlers.rst
- Documentation/DeveloperCorner/CrawlingStrategies.rst
- Documentation/Migration/Index.rst
This PR re-introduces some supported php-domain directives which got removed in #672.
> [DOCS] Re-introduce supported php-domain directives

- Tests/CGL/composer.json
- Tests/CGL/composer.lock
- Tests/CGL/phpstan-baseline.neon
- Tests/CGL/phpstan.php
- Tests/CGL/rector.php
- composer.json
- renovate.json
This PR updates all CGL tools to PHP 8.3.
> [TASK] Use PHP 8.3 for CGL tools

- Resources/Private/Libs/Build/composer.json
- composer.json
- composer.lock
Related: #809
Related: eliashaeussler/cache-warmup#465
Related: eliashaeussler/cache-warmup#468
> [BUGFIX] Sync `cuyz/valinor` conflicts with `eliashaeussler/cache-warmup`

- .qlty/.gitignore
- .qlty/qlty.toml
This pull request introduces configuration for a quality assurance tool by adding a `.gitignore` file and a `qlty.toml` configuration file. The changes define file inclusion/exclusion rules, specify test patterns, enable plugins, and configure runtime and analysis settings.
* [`.qlty/.gitignore`](diffhunk://#diff-9e9cfb22d23edcddc87b2f4c6c9d197ad2cf8b8861468bf389744eafd3c62fadR1-R6): Added rules to ignore all files except specific directories (`configs`, `hooks`) and the `qlty.toml` file. This ensures only relevant files are tracked for quality checks.
* `.qlty/qlty.toml`: Introduced a configuration file that:
- Specifies file exclusion patterns for directories like `node_modules`, `dist`, `vendor`, and others commonly used for build artifacts or dependencies.
- Defines test file patterns …
> [TASK] Add qlty config file

- composer.json
- composer.lock
Related: CuyZ/Valinor#685
Related: CuyZ/Valinor#691
> [BUGFIX] Mark `cuyz/valinor` v2.1.2 as conflicting
