composer.json

This PR adds support for `eliashaeussler/cache-warmup` 0.6.x, which was released recently.

[TASK] Declare support for eliashaeussler/cache-warmup 0.6.x

---

composer.json

This PR adds missing dependencies to `composer.json`, as reported by composer-require-checker.

[BUGFIX] Add missing dependencies to composer.json

---

composer.json

This PR adds all allowed plugins to `composer.json` to add support for Composer 2.2.

[TASK] Declare allowed plugins in composer.json (Composer 2.2)

---

Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf

This PR streamlines all locallang*.xlf files with the XLIFF 1.2 standard, which is currently supported by TYPO3 CMS.

[TASK] Streamline locallang*.xlf files with XLIFF 1.2

---

.editorconfig-lint.php
.gitattributes
.github/workflows/cgl.yaml
captainhook.json
composer.json

This PR provides a Finder instance to exclude
from `.editorconfig` linting.

[BUGFIX] Exclude generated JavaScript files from .editorconfig linting

---

.github/workflows/cgl.yaml
.github/workflows/tests.yaml

This PR limits how workflows are run:

[BUGFIX] Avoid concurrent workflow runs on pull requests

---

.github/dependabot.yml
.github/workflows/cgl.yaml
.github/workflows/tests.yaml
README.md

With this PR, support for the `develop` branch is dropped. The `main` branch will be used as main branch later on.

[TASK] Drop support for `develop` branch

---

composer.json

This PR widens the possibly installable versions of `eliashaeussler/cache-warmup` to include 0.7.x versions as well.

[FEATURE] Add support for eliashaeussler/cache-warmup 0.7.x

---

composer.json

This PR adds support for the recently published version `0.8.0` of `eliashaeussler/cache-warmup` and following patch releases.

[FEATURE] Allow installation of eliashaeussler/cache-warmup 0.8.x

---

Resources/Private/Libs/Build/composer.json

This PR aligns the version requirements for TER library dependencies with the version ranges declared in `composer.json`.

[BUGFIX] Widen version ranges for TER library dependencies

---

.github/workflows/release.yaml

This PR re-adds the build of PHAR file used for TER packaging. It seems like this was removed by accident when switching from GitLab to GitHub.

[BUGFIX] Build PHAR files for TER packaging

---

Classes/Controller/CacheWarmupController.php
Classes/Request/WarmupRequest.php
Tests/Unit/Request/WarmupRequestTest.php
composer.json

The `symfony/serializer` component is now used to denormalize the request's query params to a `WarmupRequest` object. For this, the appropriate class has been aligned with the structure of the expected query params, making it possible to directly normalize them to it.
In addition, this is a step forward to fully support PHP 8.x and pave the way for further support of the 1.x versions of the underlying `eliashaeussler/cache-warmup` library.
Resolves: #73

[BUGFIX] Use `symfony/serializer` to properly denormalize query params

---

Classes/Utility/AccessUtility.php
Resources/Private/Libs/Build/composer.json
Resources/Private/Libs/Build/composer.lock
composer.json

This PR fixes a bug where multi-language records are not properly handled in `AccessUtility::checkPagePermissions()`. The bug should have only occurred within the page tree context menu when logged in as non-admin user.

[BUGFIX] Properly handle multi-language records in AccessUtility

---

Classes/Sitemap/Provider/ProviderInterface.php
Classes/Sitemap/Provider/RobotsTxtProvider.php
Classes/Sitemap/Provider/SiteProvider.php
Classes/Sitemap/SitemapLocator.php
Configuration/Services.php
Configuration/Services.yaml
README.md

With this PR, sitemap providers are now tagged as `warming.sitemap_provider`. This allows to reference all available sitemap providers and pass them as tagged iterator to the `SitemapLocator`. This also makes it easier to provide custom sitemap implementations.

[!!!][FEATURE] Use sitemap providers as tagged iterator

---

.github/workflows/dependabot.yaml

The `dependabot.yaml` workflow needs special permissions in order for the `stefanzweifel/git-auto-commit-action` to allow amending and pushing a modified commit. An appropriate PAT is now used instead of the default Github token.

[BUGFIX] Use PAT for Dependabot workflow

---

.github/workflows/dependabot.yaml

As written in https://github.com/stefanzweifel/git-auto-commit-action#advanced-uses, the `fetch-depth` when using the `stefanzweifel/git-auto-commit-action` in combination with `git commit --amend` should be `2`. Otherwise, the created commit is created outside of the actual commit history, which causes a lot of trouble (as can be seen in #88).

[BUGFIX] Fetch last two commits in Dependabot workflow

---

Configuration/Services.yaml

The `CacheWarmupService` is considered public API. Therefore, the corresponding service in the service container is now marked as `public`.

[FEATURE] Declare `CacheWarmupService` as public service

---

.github/workflows/tests.yaml

Sometimes the required `CC_TEST_REPORTER_ID` secret for CodeClimate is not available, e.g. within forks. Since codecov already handles coverage reports, we only run CodeClimate if the appropriate secret exists.

[BUGFIX] Skip CodeClimate coverage report if secret is not available

---

Classes/Command/WarmupCommand.php
Classes/Configuration/Configuration.php
Classes/Service/CacheWarmupService.php
Documentation/Configuration/ExtensionConfiguration.rst
Documentation/DeveloperCorner/Crawlers.rst
ext_conf_template.txt

This commit adds support for configurable crawlers that were introduced with eliashaeussler/cache-warmup#59 and is available since `0.7.13` of [eliashaeussler/cache-warmup](https://github.com/eliashaeussler/cache-warmup). For this, two new extension configuration options have been added:
- `crawlerOptions` (for default crawlers)
- `verboseCrawlerOption` (for verbose crawlers)

[FEATURE] Add support for configurable crawlers

---

Classes/Configuration/Configuration.php
Documentation/DeveloperCorner/ConfigurationAPI.rst

Both `Configuration::getCrawler()` and `Configuration::getVerboseCrawler()` now fall back to the default crawler implementations in case an invalid class name is configured.

[BUGFIX] Harden Configuration API against invalid crawler class names

---

Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php

With this PR, a bug within context menu items has been fixed. Language sub-menus are not validated twice to avoid hiding possible cache warmup options for permitted users.

[BUGFIX] Assure permitted cache warmup options are shown in context menu

---

Classes/Controller/CacheWarmupController.php
Resources/Private/Partials/ToolbarItemAction.html
Resources/Private/Templates/CacheWarmupToolbarItemActions.html

This PR fixes an edge-case when non-backend users do not have access to the default language of a site. In this case, the sitemap selection in the backend toolbar was invalid. It will now show a language menu instead.

[BUGFIX] Handle missing access to default language in backend toolbar

---

Classes/Crawler/ConcurrentUserAgentCrawler.php
Classes/Crawler/ConfigurableClientTrait.php
Classes/Crawler/OutputtingUserAgentCrawler.php

This commit adds native support for the recently introduced crawler option `client_config`.
Support for this crawler was added in the upstream package `eliashaeussler/cache-warmup` with version `0.8.2` (see eliashaeussler/cache-warmup#95). Users in need for this crawler option must assure that the latest version of said upstream package is installed.
The new crawler option is only available to the default crawlers, `ConcurrentUserAgentCrawler` and `OutputtingUserAgentCrawler`. Configuration must be provided as JSON-encoded string in the appropriate extension configurations `crawlerOptions` and `verboseCrawlerOptions`.
Resolves: #85

[FEATURE] Implement crawler option "client_config"

---

.github/dependabot.yml

This PR enables daily Dependabot updates.

[TASK] Run Dependabot updates daily instead of weekly

---

Classes/Controller/CacheWarmupController.php

This patch fix a PHP warning if `websiteTitle` is not set in the site configuration and needs to be fetched from the pages table
Fixes: #125

[BUGFIX] Fix undefined array key error in fetchSitesAction

---

.github/workflows/dependabot.yaml
.github/workflows/release.yaml

With GitHub [deprecating the `set-output` commands in GitHub workflows](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), the new `$GITHUB_OUTPUT` variable needs to be used instead.

[BUGFIX] Replace deprecated job outputs in GitHub workflows

---

Classes/Utility/AccessUtility.php

PHPStan 1.9 adds support for lists, therefore we must perform a type-safe check on lists. There's currently only one candidate, `AccessUtility::checkPagePermissions()`, which is now hardened.

[BUGFIX] Double-check record when checking permissions

---

Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php
Classes/Configuration/Configuration.php
Documentation/Configuration/ExtensionConfiguration.rst
ext_conf_template.txt

Only a limited set of doktypes should be available for cache warmup in page tree context menu. This PR adds a new extension configuration to limit this set, defaulting to default pages (`1`) only.
Resolves: #161

[BUGFIX] Limit doktype support in page tree context menu

---

Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php

The context menu item provider distributed by EXT:impexp already uses priority 50. In order to avoid conflicts with said provider, we now use another priority for our provider.

[BUGFIX] Use non-conflicting priority for context menu item provider

---

Documentation/Configuration/ExtensionConfiguration.rst
Documentation/Configuration/Index.rst
Documentation/Configuration/Permissions.rst
Documentation/Configuration/SiteConfiguration.rst
Documentation/Contributing/Index.rst
Documentation/DeveloperCorner/AccessUtility.rst
Documentation/DeveloperCorner/Caching.rst
Documentation/DeveloperCorner/ConfigurationAPI.rst
Documentation/DeveloperCorner/Crawlers.rst
Documentation/DeveloperCorner/Index.rst
Documentation/DeveloperCorner/SitemapProviders.rst
Documentation/Includes.rst.txt
Documentation/Index.rst
Documentation/Installation/Index.rst
Documentation/Introduction/Index.rst
Documentation/Sitemap.rst
Documentation/Usage/BackendToolbar.rst
Documentation/Usage/ConsoleCommands.rst
Documentation/Usage/Index.rst
Documentation/Usage/PageTree.rst
Documentation/Usage/UsingTheAPI.rst
Documentation/genindex.rst

This PR streamlines indentation across the whole documentation to match TYPO3 coding standards (4 spaces).

[DOCS] Streamline indentation to 4 spaces

---

Resources/Private/Libs/Build/composer.json
Resources/Private/Libs/Build/composer.lock
composer.json

This PR drops support for `eliashaeussler/cache-warmup` 0.4.x since this version is pretty outdated and makes it hard to test the crawling behavior.

[!!!][TASK] Drop support for eliashaeussler/cache-warmup 0.4.x

---

Classes/Utility/AccessUtility.php
Documentation/Configuration/Permissions.rst

User TSconfig for cache warmup may now contain recursively accessible pages. For this, a plus sign (`+`) must be added to a page id to allow cache warmup for all subpages of this page.
Example:
```
options.cacheWarmup.allowedPages = 1,72+
```
In this example, the pages with 1 and 72 as well as all subpages of page 72 can be warmed up.

[FEATURE] Allow configuration of recursively accessible pages

---

Classes/Sitemap/Provider/AbstractProvider.php
Tests/Unit/Sitemap/Provider/SiteProviderTest.php

XML sitemap paths may now contain a query string. This comes in handy if – for example – only a specific sitemap should be crawled rather than all sitemaps.

[BUGFIX] Support query string in XML sitemap path

---

.gitattributes
packaging_exclude.php

The `CODE_OF_CONDUCT.md` file is only relevant when contributing to this project.

[TASK] Exclude `CODE_OF_CONDUCT.md` from dist files

---

Classes/Command/WarmupCommand.php

In order to properly mimic the behavior of the upstream `cache-warmup` command, sub-command input parameters are now always passed as scalar values. In addition, the input option `limit` is now properly resolved to a positive integer.
Resolves: #239

[BUGFIX] Pass scalar values to sub-command

---

renovate.json

This PR switches the used Renovate preset from `default.json` to `typo3-extension.json`, see eliashaeussler/renovate-config#24.

[TASK] Use Renovate TYPO3 extension preset

---

Classes/Utility/AccessUtility.php

This PR hardens the page permission check for pages in `AccessUtility`. If any page is hidden, even users with admin privileges can no longer warmup those pages.

[BUGFIX] Properly check for hidden pages in `AccessUtility`

---

Classes/Controller/FetchSitesController.php
Resources/Private/Partials/Modal/Alert/NoSites.html
Resources/Private/Templates/Modal/SitesModal.html

When no sites are available for cache warmup, the cache warmup modal shows an appropriate notice together with a linked button to the sites module. However, this module is not accessible for non-admins and is now hidden for these users.

[BUGFIX] Don't render button to sites module for non-admins

---

.gitattributes
.github/workflows/cgl.yaml
Documentation/Configuration/Index.rst
Documentation/Configuration/TypoScriptConfiguration.rst
composer.json
ext_typoscript_constants.typoscript
ext_typoscript_setup.typoscript
packaging_exclude.php
typoscript-lint.yml

This PR introduces a global TypoScript configuration that allows to override Fluid templates used in EXT:warming. The following TypoScript constants are now available:
```
module.tx_warming {
view {
templateRootPath =
partialRootPath =
}
}
```
Related: #174

[FEATURE] Provide TypoScript configuration for Fluid templates

---

.github/workflows/tests.yaml

Acceptance tests may fail from time to time due to timeouts. With this PR, those failed tests are now retried one time in CI. This cannot be done for the coverage job as well as it would provide an incomplete coverage report.

[BUGFIX] Retry failed acceptance tests in CI

---

Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php
Classes/Cache/SitemapsCache.php
Classes/Command/WarmupCommand.php
Classes/Controller/FetchSitesController.php
Classes/Service/CacheWarmupService.php
Classes/Sitemap/Provider/DefaultProvider.php
Classes/Sitemap/Provider/PageTypeProvider.php
Classes/Sitemap/Provider/Provider.php
Classes/Sitemap/Provider/RobotsTxtProvider.php
Classes/Sitemap/Provider/SiteProvider.php
Classes/Sitemap/SitemapLocator.php
Documentation/DeveloperCorner/Caching.rst
Documentation/DeveloperCorner/SitemapProviders.rst
Documentation/Migration/Index.rst
Resources/Private/Partials/Modal/Sites/SiteGroup.html
Tests/Acceptance/Backend/ContextMenu/ItemProviders/CacheWarmupProviderCest.php
Tests/Build/Configuration/sites/root-2/config.yaml
Tests/Functional/Cache/SitemapsCacheTest.php
Tests/Functional/Sitemap/Provider/PageTypeProviderTest.php
Tests/Functional/Sitemap/SitemapLocatorTest.php
Tests/Unit/Sitemap/Provider/DefaultProviderTest.php
Tests/Unit/Sitemap/Provider/RobotsTxtProviderTest.php
Tests/Unit/Sitemap/Provider/SiteProviderTest.php

This PR changes the way how sitemaps are located in order to support multiple sitemaps being returned by sitemap providers. This is especially useful when using a `robots.txt` file with multiple `Sitemap` declarations. Prior to this change, only the first sitemap was respected. With this PR, all declared sitemaps are now returned.
⚠️ This is a breaking change as it changes the method signature in `EliasHaeussler\Typo3Warming\Sitemap\Provider\Provider::get()`.
Related: #199

[!!!][FEATURE] Support multiple sitemaps to be located

---

.github/workflows/tests.yaml

This PR uses the `nick-fields/retry` action to retry failed acceptance tests.

[BUGFIX] Stabilize acceptance tests in CI

---

packaging_exclude.php

When packaging for TER, the `Configuration` directory was excluded by accident. This is now fixed and the directory should be included again.

[BUGFIX] Don't exclude `Configuration` directory in TER package

---

Classes/Sitemap/Provider/PageTypeProvider.php
Tests/Functional/Sitemap/Provider/PageTypeProviderTest.php

The previous implementation of the `PageTypeProvider` only respected the identifier `PageTypeSuffix` for configuration of the `PageType` enhancer. However, any identifier is supported in TYPO3 core for route enhancers. All other identifiers were therefore ignored by the `PageTypeProvider`.
This is now fixed and all enhancer configurations are respected. With this PR, the following enhancer configurations are accepted:
```yaml
routeEnhancers:
PageTypeSuffix:
type: PageType
map:
'sitemap.xml': 1533906435
```
```yaml
routeEnhancers:
foo:
type: PageType
map:
'sitemap.xml': 1533906435
```

[BUGFIX] Support custom identifiers for PageType enhancer

---

renovate.json

The TYPO3 extension preset no longer extends from the default preset, therefore both presets must be included explicitly.

[TASK] Use default Renovate preset next to TYPO3 extension preset

---

Documentation/DeveloperCorner/Crawlers.rst

This PR adds missing documentation for streamable crawlers that were introduced with `1.0.0`.

[DOCS] Document streamable crawlers

---

Classes/ValueObject/Request/WarmupRequest.php
Tests/Functional/Controller/CacheWarmupLegacyControllerTest.php
Tests/Functional/Http/Message/Event/WarmupFinishedEventTest.php
Tests/Unit/ValueObject/Request/WarmupRequestTest.php

This PR fixes the `WarmupRequest` value object to be able to actually map the request id from request query parameters to the object during hydration.

[BUGFIX] Extract warmup request id from query parameters

---

ext_emconf.php

This PR removes an outdated configuration option from `ext_emconf.php` as suggested by Rector.

[TASK] Drop outdated configuration from `ext_emconf.php`

---

Resources/Private/Libs/Build/composer.json
Resources/Private/Libs/Build/composer.lock
composer.json

This PR normalizes the dependency version constraint for `eliashaeussler/cache-warmup` in order to make `ergebnis/composer-normalize` happy. In addition, the packaged version of `eliashaeussler/cache-warmup` is updated to the latest version.

[BUGFIX] Normalize dependency version constraint

---

Classes/Utility/AccessUtility.php

[BUGFIX] Properly check for hidden pages in AccessUtility

---

Classes/Cache/SitemapsCache.php
Documentation/DeveloperCorner/Caching.rst
Tests/Functional/Cache/SitemapsCacheTest.php
phpstan-baseline.neon

This PR improves handling of sitemaps cache by using a separate cache entry for each site. This way, the complete Caching API of TYPO3 can be used to modify cache entries, instead of re-implementing several filesystem-based parts (reading, writing, manipulating) on our own.

[TASK] Improve sitemaps cache handling

---

Classes/Cache/SitemapsCache.php
Classes/EventListener/SiteConfigurationListener.php
Configuration/Services.yaml
Tests/Functional/Cache/SitemapsCacheTest.php
Tests/Functional/EventListener/SiteConfigurationListenerTest.php

This PR adds an event listener to remove a sitemaps cache entry if the associated site's configuration is changed. This effectively triggers a new site resolving which takes the modified site properties into account.

[BUGFIX] Invalidate sitemaps cache when site config changes

---

.ddev/commands/web/init-typo3

TYPO3 12.4.6 requires a server-type to be configured when using the `typo3 setup` command non-interactively. This PR adds the appropriate configuration as environment variable.

[BUGFIX] Configure server-type in `ddev init-typo3` command

---

.github/workflows/cgl.yaml

A new step is added to the CGL workflow that validates Frontend asset integrity. It re-builds Frontend assets and checks if any changes were made.

[TASK] Check Frontend asset integrity in CGL workflow

---

.github/workflows/assets.yaml

This PR adds a new workflow that rebuilds and pushes Frontend assets if asset integrity check fails.

[TASK] Automatically rebuild Frontend assets on Renovate updates

---

Classes/Command/WarmupCommand.php
composer.json

This PR now passes TYPO3's client to the underlying sub-command when running the `warming:cachewarmup` command. This assures that globally configured HTTP options are used.

[BUGFIX] Inject TYPO3's client into sub-command

---

.github/workflows/assets.yaml

This PR changes the way how the `actions/checkout` is used to rebuild frontend assets: The current head ref is now explicitly checked out to properly commit changes.

[BUGFIX] Checkout explicit ref when rebuilding assets

---

Tests/Build/Configuration/system/additional.php

This PR disables BE login rate limit for development by setting `[BE][loginRateLimit] = 0` in `additional.php`.

[TASK] Disable login rate limit for development

---

Tests/Build/Configuration/system/additional.php

This PR additionally configures `[BE][loginRateLimitIpExcludeList] = '*'` to assure login rate limit is disabled for local development.
This is a follow-up to #498.

[BUGFIX] Assure disabled login rate limit for local development

---

Classes/Command/WarmupCommand.php
Classes/Configuration/Configuration.php
Classes/Service/CacheWarmupService.php
Documentation/Configuration/ExtensionConfiguration.rst
Tests/Functional/Command/WarmupCommandTest.php
Tests/Functional/Configuration/ConfigurationTest.php
Tests/Functional/Fixtures/Classes/DummyGuzzleClientFactory.php
Tests/Functional/Service/CacheWarmupServiceTest.php
ext_conf_template.txt

This PR introduces a new extension configuration `parserClientOptions`. It accepts a JSON-encoded string of Guzzle client options which is passed to the client used within the XML parser to parse XML sitemaps.

[FEATURE] Allow configuration of XML parser client options

---

composer.json

This PR fixes a bug with latest xdebug version where a globally configured `XDEBUG_MODE` is not properly respected. It can be reverted once a dedicated xdebug release is pushed and included in DDEV.

[BUGFIX] Assure XDEBUG_MODE is set when running tests with coverage

---

Resources/Private/Frontend/src/scripts/backend/modal/element/report-panel.ts
Resources/Private/Frontend/src/scripts/backend/modal/element/report-summary-card.ts
Resources/Private/Frontend/src/scripts/backend/modal/progress-modal.ts
Resources/Private/Frontend/src/scripts/backend/modal/report-modal.ts
Resources/Private/Frontend/src/scripts/backend/modal/sites-modal.ts

This PR changes the return type of custom `Lit` element implementations to always return an instance of `HTMLElement` classes. This is necessary to be in line with recent method signature changes in `Lit`.

[BUGFIX] Specify correct return type for `renderRoot()` implementations

---

.ddev/config.yaml
.github/workflows/assets.yaml
.github/workflows/cgl.yaml

This PR explicitly sets the Node.js version to `20`, both in DDEV web server as well as GitHub workflows relying on Frontend asset handling.

[TASK] Use Node 20 in DDEV and GitHub workflows

---

Resources/Private/Frontend/package.json

This PR adds the `--failAfterWarnings` flag to Rollup to fail if any warning occurs during Frontend build. This allows to catch build warnings early, especially on automated Renovate updates.

[BUGFIX] Fail if Frontend build generates warnings

---

.github/workflows/tests.yaml
composer.json

This PR switches back to PHP 8.2 in test coverage job since using PHP 8.3 is erroneous.

[BUGFIX] Use PHP 8.2 for test coverage job

---

.github/workflows/cgl.yaml
.github/workflows/tests.yaml

This PR changes the retry of failing tests in test workflow from one retry to two retries. This should stabilize test workflow a little bit (hopefully).

[TASK] Retry failing tests multiple times in CI

---

Classes/Command/WarmupCommand.php
Documentation/Usage/ConsoleCommands.rst
Tests/Functional/Command/WarmupCommandTest.php
Tests/Functional/Fixtures/Files/cache-warmup.yaml

This PR adds a new command option `-c|--config` to the `warming:cachewarmup` command. It allows to reference an external config file which holds additional configuration options. The new command option is in line with the [official command option](https://cache-warmup.dev/config-reference/config.html).

[FEATURE] Support config files in cache warmup command

---

Classes/Command/WarmupCommand.php
Documentation/Usage/ConsoleCommands.rst
Tests/Functional/Command/WarmupCommandTest.php
Tests/Functional/Fixtures/Files/sitemap_de_2.xml
Tests/Functional/Fixtures/Files/sitemap_en_2.xml
Tests/Functional/Fixtures/Files/sitemap_fr_2.xml
Tests/Functional/SiteTrait.php

This PR extends the existing `--sites` command option by a special keyword `all`. When used, all available sites are warmed up.
Resolves: #717

[FEATURE] Allow warming up all available sites at once

---

.ddev/addon-metadata/ddev-selenium-standalone-chrome/manifest.yaml
.ddev/docker-compose.selenium-chrome.yaml

This PR updates the `ddev/ddev-selenium-standalone-chrome` add-on to the latest version.

[TASK] Update `ddev-selenium-standalone-chrome` add-on to v1.1.0

---

Classes/Crawler/ConcurrentUserAgentCrawler.php
Classes/Crawler/OutputtingUserAgentCrawler.php
Classes/Http/Client/Handler/SubRequestHandler.php
Documentation/Configuration/CrawlerConfiguration.rst
Documentation/Configuration/Index.rst
Tests/CGL/phpstan-baseline.neon
Tests/Functional/Crawler/ConcurrentUserAgentCrawlerTest.php
Tests/Functional/Crawler/OutputtingUserAgentCrawlerTest.php
Tests/Functional/Http/Client/Handler/SubRequestHandlerTest.php
composer.json
composer.lock

This PR introduces a `SubRequestHandler`. It can be used in the default crawlers to perform cache warmup requests with the bootstrapped frontend application instead of sending real HTTP requests.

[FEATURE] Introduce sub request handler

---

Resources/Private/Frontend/rollup.config.js
Resources/Private/Frontend/src/styles/modal.scss

The [`@import` statement is deprecated](https://sass-lang.com/documentation/breaking-changes/import/) and will be removed with Dart Sass 2.0. Thus, it is now migrated to its successor `@use`.

[TASK] Migrate deprecated sass `@import` statement

---

ext_tables.sql

This PR removes the default value for `tx_warming_domain_model_log.url` since DBMSs like MySQL don't support default values for `TEXT` columns.
Resolves: #729

[BUGFIX] Remove default value for `tx_warming_domain_model_log.url`

---

Classes/Backend/ContextMenu/ItemProviders/CacheWarmupProvider.php
Classes/Domain/Repository/SiteLanguageRepository.php
Classes/Domain/Repository/SiteRepository.php
Classes/Security/Context/PermissionContext.php
Classes/Security/WarmupPermissionGuard.php
Tests/Functional/Security/Context/PermissionContextTest.php
Tests/Functional/Security/WarmupPermissionGuardTest.php

With this PR, the current backend user is now used by default in `PermissionContext` if no explicit user is defined.

[TASK] Use current backend user by default in `PermissionContext`

---

Classes/Configuration/Configuration.php
Classes/Http/Client/ClientBridge.php
Configuration/Services.yaml
Documentation/Configuration/ExtensionConfiguration.rst
Documentation/Migration/Index.rst
Tests/Functional/Configuration/ConfigurationTest.php
Tests/Functional/Http/Client/ClientBridgeTest.php
ext_conf_template.txt

This PR introduces a new extension configuration `clientOptions`. It can be used to configure the global client instance used in crawlers and the XML parser to fetch external content.
> [!IMPORTANT]
> Existing client configuration must be migrated from `crawlerOptions:client_config`, `verboseCrawlerOptions:client_config` and `parserClientOptions` to `clientOptions`. Read more in the documentation.

[FEATURE] Introduce client options extension configuration

---

Classes/Http/Message/PageUriBuilder.php
Configuration/Services.yaml

This PR makes the dependency to `PageRepository` lazy to avoid executing DB queries during object construction (in early state).

[BUGFIX] Make dependency to `PageRepository` lazy

---

Classes/View/TemplateRenderer.php

This PR migrates the template rendering in `TemplateRenderer` to use the new `ViewFactory` in TYPO3 v13. The old behavior is kept for TYPO3 v12.

[TASK] Use ViewFactory in TYPO3 v13 to create view

---

Classes/Command/WarmupCommand.php
Classes/DependencyInjection/CrawlingStrategyCompilerPass.php
Configuration/Services.php
Configuration/Services.yaml
Resources/Private/Libs/Build/composer.json
Tests/Functional/Command/WarmupCommandTest.php
composer.json
composer.lock

This PR fixes a behavior in `warming:cachewarmup` command which made it impossible to use custom crawling strategies on the command line.
Resolves: #787

[BUGFIX] Allow custom crawling strategies on command line

---

Configuration/TSconfig/Page.tsconfig

With https://github.com/TYPO3/typo3/commit/27c38f78d94a6b20a4d50f537b3276abc0b26caa, generation of preview buttons was hardened. We now need a dedicated TSconfig option to explicitly enable preview URL generation.

[BUGFIX] Ensure preview button is generated for log records
